# 数据模块
database:
  # 存储类型
  type: local
  # 本地存储路径，默认为插件目录下
  storage: ""

# 选项
options:
  # 展示冷却时间（单位: 秒）
  cooldown: 10
  # 玩家头颅物品名称
  # {0} = 玩家名称
  head: "&6{0}"
  # 展示界面标题
  # {0} = 玩家名称
  title: "&6{0} &8背包"